In [1]:
import numpy as np 

In [3]:
! pip install numpy

In [4]:
arr = np.array([1,2,3,4])

In [7]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.full((3,4),1)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [11]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [15]:
np.arange(1,100,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [21]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [23]:
myarr = np.array([[1,2,3],[2,3,4],[5,6,7]])

In [25]:
myarr

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [27]:
myarr.shape

(3, 3)

In [31]:
myarr.size

9

In [33]:
myarr.dtype

dtype('int32')

In [36]:
myarr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [11, 12, 13]], dtype='float32')

In [38]:
myarr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [11., 12., 13.]], dtype=float32)

In [42]:
myarr.shape

(4, 3)

In [44]:
reshaped = myarr.reshape((3,4))

In [46]:
myarr.flatten()

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 11., 12., 13.],
      dtype=float32)

In [49]:
myarr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [11., 12., 13.]], dtype=float32)

In [51]:
np.sum(myarr, axis=1)

array([ 6., 15., 24., 36.], dtype=float32)

In [57]:
myarr[0][1]

2.0

In [63]:
myarr[0:2, 1:3]

array([[2., 3.],
       [5., 6.]], dtype=float32)

In [66]:
result = myarr**2

In [70]:
result+10

array([[ 11.,  14.,  19.],
       [ 26.,  35.,  46.],
       [ 59.,  74.,  91.],
       [131., 154., 179.]], dtype=float32)