In [1]:
# • Create a NumPy array with values from 10 to 100 and print its shape
import numpy as np
import time

arr = np.array(range(10,101))

print("Shape: ", arr.shape)
print(type(arr))

Shape:  (91,)
<class 'numpy.ndarray'>


In [51]:
# Compare the time taken to multiply two Python lists vs. two NumPy arrays.
arr1 = np.array(range(10000))
arr2 = np.array(range(10000))

start = time.time()
result = arr1 * arr2
end = time.time()
print("Total Time: ", end - start)

# List Time
l1 = list(range(10000))
l2 = list(range(10000))

start = time.time()
result = [x * y for x,y in zip(l1, l2)]
end = time.time()
print("Total Time: ", end - start)

Total Time:  0.0009984970092773438
Total Time:  0.0010035037994384766


In [25]:
# Find the memory size of a NumPy array with 1 million elements
import sys

list_data = list(range(1000000))
numpy_data = np.array(list_data)
print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8000056000000 bytes
NumPy array size: 4000000 bytes


In [49]:
# Note :  Slicing returns a view, not a copy! Changes affect the original array
import numpy as np
original = np.array([1, 2, 3, 4, 5])

sliced = original[1:4]
print("Sliced array:", sliced)
sliced[0] = 999

print("Sliced array:", sliced)
print("Original array:", original)  # ORIGINAL IS CHANGED TOO!

Sliced array: [2 3 4]
Sliced array: [999   3   4]
Original array: [  1 999   3   4   5]


In [63]:
# Create a 3×3 array filled with random numbers and print its shape.
arr = np.random.rand(3, 3)
print("Array:\n", arr)
print("Shape: ", arr.shape)

Array:
 [[0.22675014 0.54867776 0.41925199]
 [0.65293456 0.65880398 0.14737023]
 [0.2150127  0.41601164 0.84282712]]
Shape:  (3, 3)


In [77]:
# Convert an array of floats [1.1, 2.2, 3.3] into integers.
arr = np.array([1.1, 2.2, 3.3])
arr = arr.astype(np.int32)
print(type(arr))

<class 'numpy.ndarray'>


In [79]:
#  Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6] .
arr = np.array([10, 20, 30, 40, 50])
idx = [0, 2, 4]
print(arr[idx])

[10 30 50]


In [86]:
#  Reshape a 1D array of size 9 into a 3×3 matrix.
arr = np.arange(9)  # [0, 1, 2, 3, 4, 5, 6, 7, 8]
print("Shape:", arr.shape)  # (9,)

matrix = arr.reshape(3, 3)
print("Shape:", matrix.shape)  # (3, 3)

Shape: (9,)
Shape: (3, 3)


In [96]:
#  Use boolean masking to filter numbers greater than 50 in an array 
arr = np.array([10, 25, 60, 45, 80, 30, 95, 50, 70])
mask = arr > 25
#print(mask) #Output: [False False  True False  True False  True False  True]
print(arr[mask]) #Output: [30 40 50]
# OR
filtered = arr[arr > 50]
print("Numbers > 50:", filtered)

[60 45 80 30 95 50 70]
Numbers > 50: [60 80 95 70]
